name: hedgehog-raspi-build-docker-wrap-push-ghcr

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'malcolm-iso/**'
      - 'hedgehog-raspi/**'
      - 'shared/bin/*'
      - '.trigger_iso_workflow_build'
      - '.github/workflows/raspi-build-push.yml'
      - '.github/workflows/hedgehog-raspi-build-docker-wrap-push-ghcr.yml'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rpi_model: [4, 5]
    uses: ./.github/workflows/raspi-build-push.yml
    permissions:
      actions: write
      packages: write
      contents: read
      security-events: write
    with:
      profile: hedgehog
      rpi_model: ${{ matrix.rpi_model }}
      rpi_os: trixie